### ISSUE TITLE
Automated Testing Sim Error (6/7/2016 10:00 AM)

### ISSUE THREAD

**Issue by phet-steele** [phetsims/plinko-probability#24]
@Denz1994 I believe this commit https://github.com/phetsims/plinko-probability/commit/dcdfd2f19f7a1af96a55c798148d11fd972bcfc1 is throwing the following error. The sim will no longer load if the images used are the incorrect aspect ratio:

```
Uncaught Error: Assertion failed: NavigationBar icons for screen 0 did not have a valid aspect ratio.
Error: Assertion failed: NavigationBar icons for screen 0 did not have a valid aspect ratio.
    at window.assertions.assertFunction (http://phettest.colorado.edu/assert/js/assert.js:23:13)
    at new NavigationBar (http://phettest.colorado.edu/joist/js/NavigationBar.js?bust=1465317147925:77:19)
    at new Sim (http://phettest.colorado.edu/joist/js/Sim.js?bust=1465317147925:408:26)
    at http://phettest.colorado.edu/plinko-probability/js/plinko-probability-main.js?bust=1465317147925:38:15
    at window.phetLaunchSimulation (http://phettest.colorado.edu/joist/js/SimLauncher.js?bust=1465317147925:45:11)
    at doneLoadingImages (http://phettest.colorado.edu/joist/js/SimLauncher.js?bust=1465317147925:53:18)
    at Object.launch (http://phettest.colorado.edu/joist/js/SimLauncher.js?bust=1465317147925:107:9)
    at http://phettest.colorado.edu/plinko-probability/js/plinko-probability-main.js?bust=1465317147925:37:15
    at Object.execCb (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:1650:25)
    at Object.check (http://phettest.colorado.edu/sherpa/lib/require-2.1.11.js:866:35)
```

**Comment by Denz1994** [comment]
I used some images as place holders for the icons in the nav-bar and homescreen, which is what caused the error. The actual icons to be used are detailed by issue #23 and at this time have yet to be decided on.

They have been reverted back to white boxes to satisfy the assertion error 1559ddbb1d9ffa0092eb63863620116ac228bdfa .

**Comment by phet-steele** [comment]
Thank you, @Denz1994.
